### ISSUE TITLE
Pocket, Futon and the App all overwrite each other's sessions

### ISSUE THREAD

**Issue by espy** [hoodiehq/hoodie-server#134]
To reproduce: 

1. Start the default hoodie app, sign up as "test". It says "Hello, test"
2. Open Pocket in another tab, sign in as admin
3. Reload first tab. It says "Hello, admin"

Futon is also involved:

4. Open Futon. You'll already be signed in as admin
5. Sign out in the app tab and sign in to the app again as "test"
6. Open Futon. See "Welcome user/test!"

But it also works in the other direction:

7. Sign out of Futon and sign in again as the real admin
8. Reload app tab: you'll be signed in as admin again

I'm adding this to the plugin milestone because it makes working with plugins in Pocket  a bit tricky.

**Comment by boennemann** [comment]
Bearer Tokens landed
