### ISSUE TITLE
hoodie fails to create new app

### ISSUE THREAD

**Issue by arky** [hoodiehq/hoodie-server#156]
$ hoodie new osm-app

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.2.7 (node v0.10.20, npm 1.3.11, platform: linux)

Cloning into 'osm-app'...
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 24 (delta 0), reused 17 (delta 0)
Unpacking objects: 100% (24/24), done.
[hoodie] Replaced package.json
[hoodie] removing .git folder
npm WARN package.json osm-app@1.0.0 No repository field.
npm ERR! Error: EACCES, mkdir '/home/arky/tmp/npm-3907-GJpRmKg1'
npm ERR!  { [Error: EACCES, mkdir '/home/arky/tmp/npm-3907-GJpRmKg1']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/arky/tmp/npm-3907-GJpRmKg1' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.8.0-31-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/arky/Dev/Hoodie/osm-app
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /home/arky/tmp/npm-3907-GJpRmKg1
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/arky/tmp/npm-3907-GJpRmKg1'

$ echo $?
130

$ nodejs -v
v0.10.20

$ lsb_release -a
LSB Version:    core-2.0-ia32:core-2.0-noarch:core-3.0-ia32:core-3.0-noarch:core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 13.04
Release:    13.04
Codename:   raring

**Comment by soomro** [comment]
Version: 0.6.3 (node v0.12.0, npm 2.5.1, platform: darwin)

Initializing...

ERR! Error: EACCES, mkdir '/Users/USER/Git_Files/MYAPP_Hoodie/MYAPP/data'
ERR!     at Error (native)

Hello everyone. 
I am new to Hoodie, and this is my first app.
While running the app, i am getting this error.

When applied sudo, it gave following:
[hoodie] Hoodie does not support being run as sudo. Please try again.

What should i do?

**Comment by gr2m** [comment]
@arky woohoo Arky! Looking into Hoodie again? Ping me if you run into any blockers :)
