### ISSUE TITLE
Cloudant Support

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-server#171]
Make sure Hoodie runs fine on Cloudant.

**Comment by janl** [comment]
the new architecture will not depend on _users being exposed to the client, so we should™ be fine then

**Comment by doublerebel** [comment]
In case anyone finds this and needs such a tool, here's a JS module I created a while back for Cloudant _users db: https://github.com/doublerebel/cloudant-user

Available from npm as **cloudant-user**.
