### ISSUE TITLE
custom session handling?

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#184]
I have several issues with Hoodie using cookies for sessions at the moment. One being, that I cannot end the session if the user is offline, but there are valid use cases for that, see https://github.com/hoodiehq/hoodie.js/issues/194

There are other reason, including security flaws, why I'd suggest to have that changed.

Instead of using cookies, I'd like to send a custom header with every request, something like `X-Hoodie-Session-Id`.

Does CouchDB support something like that? Or would that mean that we have to build our own session/auth handler?

**Comment by svnlto** [comment]
I believe we have already implemented a solution for this?

**Comment by gr2m** [comment]
yes, we have bearer token now, we don't use Cookies anymore. So closing this.
