### ISSUE TITLE
starting hoodie app in parallel crashes the running process

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#185]
1. run `npm start` (or `hoodie start`) in `~/myApp$`
2. once it is running, open an new tab, repeat step one 1.
3. hoodie dies with this message:

```
Stopping CouchDB...
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by boennemann** [comment]
Now fails with port already in use, doesn't crash first app.
