### ISSUE TITLE
support /_api/_plugins/name as well as /_api/_plugins/name/

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-server#221]

**Comment by boennemann** [comment]
@janl You have access to the `server` instance now, writing a test with `inject` should work now: https://github.com/hoodiehq/hoodie-server/blob/next/lib/index.js#L41

**Comment by boennemann** [comment]
Relevant once plugins come back: https://github.com/hoodiehq/hoodie-server/issues/417
