### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by Acconut** [hoodiehq/hoodie-server#275]
Grunt now uses [AppVeyor](http://www.appveyor.com/) for testing on Windows (https://twitter.com/gruntjs/status/466058297972228096).

I would recommend setting it up for hoodie-server (and hoodie-cli, eventually).

Any opinions about it?

**Comment by ajstein** [comment]
So just to be clear, you need someone who:

- Understands [Windows installation practices](https://wix.codeplex.com/).
- Can automate the build and configuration of Erlang on Windows.
- Can automate the build, installation, and configuration of CouchDB on Windows.
- Can automate the build, installation, and configuration Node on WIndows.
- Can automate the builld, installation, and configuration of hoodie on Windows.

I am roughy familiar with all these things, and I do a lot of Windows sysadmin in my day job.  Shall I take a crack at it?

**Comment by ajstein** [comment]
I started doing some quick perusing and I found this template, relying on what seems like CI builds from Apache of CouchDB from bintray.

https://github.com/couchapp/couchapp/blob/master/appveyor.yml

**Comment by gr2m** [comment]
@ajstein welcome Alexander :wave: We are working on a new Hoodie version, you can give it a spin with this repository: https://github.com/hoodiehq/hoodie-app-tracker if you could check that it works on windows, that’d be ace. If you could help us with a CI setup using AppVeyor, that’d be really cool

**Comment by ajstein** [comment]
I saw it is a low frequency later and chore ranking.  So it is safe for me to presume time frame is not super urgent, yes?

**Comment by gr2m** [comment]
absolutely :) The issue is 2 years old, it can wait ;) Thanks a lot for looking into it. It’s great timing, too, as we plan to release the new Hoodie "Camp Release" Version soon.
