### ISSUE TITLE
plugins: allow frontend extension to require own node_modules

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#281]
let's say that is my plugin

```
hoodie-plugin-pommes
|-package.json
|-hoodie.pommes.js
|-node_modules
  |-ketchup
```

in hoodie.pommes.js, I want to

```
var Ketchup = require('ketchup')
```

That currently results in an error. If I add the `ketchup` module as dependency of my app it works

**Comment by gr2m** [comment]
@svnlto would it make everything simpler if we'd require the plugins frontend code to be bundled into `hoodie.js` to be commonJS modules?

So instead of

```js
Hoodie.extend(function(hoodie, lib, utils) {...})
```

It would be 

```js
module.exports = function(hoodie, lib, utils) {...}
```

That should make things simpler, as we wouldn't need the intermediate concatenation step, right?

**Comment by svnlto** [comment]
we'd need to change the browserify config slightly to include hoodie plugins but AFAIK we have a list of em available anyways so I doubt it'd be hard. I like the idea.

**Comment by gr2m** [comment]
To add to the idea: how about we use (or even require) the `"browser"` property in package.json to tell the path of the JavaScript that is supposed to be bundled into hoodie.js? We kinda would follow the convention, `"main"` being entry path for Node.js, `"browser"` the entry path for the browser.

**Comment by gr2m** [comment]
Let's say we require the `browser` property for plugins that want frontend code to be bundled into `hoodie.js`. This way, we can differentiate between new plugins following the new syntax and old ones.

Is there any way to somehow make the old syntax still work? Maybe using a custom browserify transform? I don't have experience with how the transformers work

**Comment by janl** [comment]
I’d be fine with forcing plugins to update.

**Comment by gr2m** [comment]
@christophwitzko wanna look into this one? I'm happy to assist

**Comment by christophwitzko** [comment]
@gr2m Sure. I will have to take a look at the 'hoodie pack' functionality first.
But besides that, browserify has a `basedir` and a `paths` option.
https://github.com/substack/node-browserify/#browserifyfiles--opts

**Comment by gr2m** [comment]
cool! What we want to do is to export proper modules as described in https://github.com/hoodiehq/hoodie-server/issues/281#issuecomment-71333443. That should also fix our speed issue that we currently have with generating the hoodie.js on the first call. Does that make sense?

**Comment by boennemann** [comment]
This was fixed by requiring plugins, rather than copying their code into the bundle template.
