### ISSUE TITLE
Authentication problem for 301 Redirect: Hoodie URL -> CouchDB URL

### ISSUE THREAD

**Issue by kaalita** [hoodiehq/hoodie-server#290]
Hi,
I'm currently trying to figure out why HOOHoodie (Hoodie for iOS) doesn't sync with the Hoodie Server for some users. The synching works for me, but while looking more closely into the HTTP requests to the backend, I stumbled over a 401 error, when trying to access the _design/permissions document in the users database. 

When trying to retrieve:
```
GET localhost:6001/_api/user%2Fdv5e5qu/_design%2Fpermissions?rev=1-06eb926f0e98c012f2c8a6aec18088df&revs=true&attachments=true HTTP/1.1
```
The server responds with a 301 redirect to:
```
http://127.0.0.1:6003/user%2Fdv5e5qu/_design/permissions?rev=1-06eb926f0e98c012f2c8a6aec18088df&revs=true&attachments=true
```
The GET request to that URL returns a 401 error, although my user is authorised and authenticated.
I don't know if the cause for the replication problems (for me it isn't), but I guess this is not the expected behaviour?

It seems the / in "_design/permissions" is not properly URL escaped (although fixing that returns the same error).

Here also the complete HTTP logs from my test (sign up user, sign in, start replications)
```
http://localhost:6001/_api/_users/org.couchdb.user:user%2Fhoodie	201	PUT	localhost:6001	/_api/_users/org.couchdb.user:user%2Fhoodie	 17 ms	1.39 KB	Complete	
http://localhost:6001/_api/_session	200	POST	localhost:6001	/_api/_session	 27 ms	1.14 KB	Complete	
http://localhost:6001/_api/user%2Fdv5e5qu/_local/8ee6d57c5c07d333521609ec9168f54060f3339f	404	GET	localhost:6001	/_api/user%2Fdv5e5qu/_local/8ee6d57c5c07d333521609ec9168f54060f3339f	 15 ms	1003 bytes	Complete	
http://localhost:6001/_api/user%2Fdv5e5qu/_local/11c22b2a9c5e4e9c07edad765cd47f88bb6f81e3	404	GET	localhost:6001	/_api/user%2Fdv5e5qu/_local/11c22b2a9c5e4e9c07edad765cd47f88bb6f81e3	 16 ms	1003 bytes	Complete	
http://localhost:6001/_api/user%2Fdv5e5qu/_design%2Fpermissions?rev=1-06eb926f0e98c012f2c8a6aec18088df&revs=true&attachments=true	301	GET	localhost:6001	/_api/user%2Fdv5e5qu/_design%2Fpermissions?rev=1-06eb926f0e98c012f2c8a6aec18088df&revs=true&attachments=true	 21 ms	1.13 KB	Complete	
http://127.0.0.1:6003/user%2Fdv5e5qu/_design/permissions?rev=1-06eb926f0e98c012f2c8a6aec18088df&revs=true&attachments=true	401	GET	127.0.0.1:6003	/user%2Fdv5e5qu/_design/permissions?rev=1-06eb926f0e98c012f2c8a6aec18088df&revs=true&attachments=true	 23 ms	655 bytes	Complete	
```

Tested with Hoodie version:
Version: 0.4.14 (node v0.10.25, npm 1.3.24, platform: darwin)

**Comment by janl** [comment]
Is this still current? Please re-open if yes.
