### ISSUE TITLE
Generating hoodie.js at server start

### ISSUE THREAD

**Issue by varunnaik** [hoodiehq/hoodie-server#296]
My application takes a very long time to load after server restart, and I suspect that the generation of hoodie.js on the server is the cause of this. I don't see any reason why we should generate this file on each restart after the app has been deployed to production.

Would it be possible to generate a hoodie.js including all plugins when building the app with `grunt build`? I currently do this myself by concatenating hoodie.js and all Hoodie plugins defined in package.json into a single Javascript file.

Is this a 'recommended' way to do things, or is there a better way of accomplishing this?

cc @peetersn @gr2m

**Comment by gr2m** [comment]
This seems to be blocking https://github.com/gr2m/hoodie-pouchdb-test/issues/1 as well. Can someone tell what the state is?

**Comment by svnlto** [comment]
> We have working code for this but it needs some tests and merging.

@gr2m

**Comment by gr2m** [comment]
@caolan @svnlto Could one of you finish this up? That'd be really great

**Comment by janl** [comment]
Is this the branch? https://github.com/hoodiehq/hoodie-server/tree/pack-hoodie-cache

**Comment by svnlto** [comment]
yup

On Thursday, January 8, 2015, Jan Lehnardt <notifications@github.com> wrote:

> Is this the branch?
> https://github.com/hoodiehq/hoodie-server/tree/pack-hoodie-cache
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hoodiehq/hoodie-server/issues/296#issuecomment-69248430>
> .
>


-- 
The paper industry is in trouble.
Please print three copies of this email.

Twitter: http://twitter.com/svenlito
Github: https://github.com/svnlto

UK Mobile: +44 79 287 32020
DE Mobile: +49 15 785944551

**Comment by mmichelli** [comment]
This is still an issue.

**Comment by boennemann** [comment]
Closing in favor #362
This will land very soon.
