### ISSUE TITLE
Multiple CouchDB Processes Spawned

### ISSUE THREAD

**Issue by inator** [hoodiehq/hoodie-server#317]
When running  hoodie-server version 1.2.4, I see an extra CouchDB process spawned by the original CouchDB pid.  Earlier versions of server do not appear to exhibit this behavior.

Edit: by earlier, I mean hoodie-server v1.0.0.

**Comment by inator** [comment]
@janl - Just thought I'd check in on this.  Do you think there could be a relationship between this and issue #329?

**Comment by janl** [comment]
I don’t think so.

**Comment by boennemann** [comment]
This was probably caused by node-multicouch not starting and stopping couchdb reliably. With only spawning PouchDB's now, this does no longer apply.
