### ISSUE TITLE
There is no way to remove a task after a `hoodie.task.error` in a worker.js

### ISSUE THREAD

**Issue by louisremi** [hoodiehq/hoodie-server#323]
When it receives a new task, my server-side plugin does various things, like querying a third party API or adding documents to a `user/xxxxx` database.
Sometimes one of these "various things" fails. I can detect this error, handle it in any way I please and then propagate it to the client-side using `hoodie.task.error()` (once [hoodie.js#185](https://github.com/hoodiehq/hoodie.js/issues/185) is solved),  but I also want to get rid of the task just like `hoodie.task.success()` does. 

"Ok little task, I saw the error, the client saw the error, now clean after yourself and let's call it a day."

**Comment by boennemann** [comment]
With the current hoodie-server implementation there are no plugins/worker.js anymore. I'm moving this to it's new place: https://github.com/hoodiehq/hoodie-server-task/issues/3 so we can address it there.
