### ISSUE TITLE
Problems connecting to external couchdb

### ISSUE THREAD

**Issue by erikor** [hoodiehq/hoodie-server#330]
I have followed the instructions on deploying to nodejitsu exactly as described here: https://github.com/hoodiehq/my-first-hoodie/blob/master/README.md, but it does not work for me--it seems database connectivity fails (same symptoms as described below).  In an effort to troubleshoot, I am now simply trying to get my local hoodie app to connect to my remote couchdb at iriscouch.com.

I have created the template app with `hoodie new myapp`, and everything works properly locally after `hoodie start`.

However, if I then set the following environment variables (password redacted):

export COUCH_URL=http://couch-ericjkort-7823786411.iriscouch.com:5984
export HOODIE_ADMIN_USER=admin
export HOODIE_ADMIN_PASS=xxxxxxxx

And do hoodie start, the result is:

```
Version: 0.6.3 (node v0.10.33, npm 2.1.8, platform: linux)

Initializing...
Using remote CouchDB: http://couch-ericjkort-7823786411.iriscouch.com:5984
Waiting for CouchDB [-*----] SUCCESS 
WWW:    http://127.0.0.1:6007
Admin:  http://127.0.0.1:6008
Starting Plugin: 'hoodie-plugin-appconfig'
Starting Plugin: 'hoodie-plugin-email'
Starting Plugin: 'hoodie-plugin-users'
All plugins started.

Error confirming user: Error: not_found
missing
{ [Error: not_found
missing]
  error: 'not_found',
  reason: 'missing',
  response: 
...
```
Which looks exactly the same as when I start with local couchdb (including the not_found error).  Removing the admin user from _users eliminates the not_found error both when I am using the local couchdb as well as the remote couchdb (as described in #276).

However, even after resolving the not_found error, it then takes a long time (about 1 minute) for the Sign Up button to appear when using the remote couchdb, presumably because the sign-in check is trying but failing, and the Sign Up form does not work (clicking Sign Up on the sign up form hangs, and the user is never created in the database.)  Tasks are not written to the database either.  I have confirmed that the database is running at the above URL.

When the Sign Up button does appear, the following errors are reported in the browser console:

```
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH http://127.0.0.1:6007/_api/?hoodieId=3cfby9h
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH http://127.0.0.1:6007/_api/_session
GET http://127.0.0.1:6007/_api/?hoodieId=3cfby9h net::ERR_CONTENT_LENGTH_MISMATCH 
```

Nothing is reported at that point in the terminal where `hoodie start --verbose` is running.

CORS is enabled in the iriscouch server, with `enable_cors` = true, `origins` = *, and `credentials` = true.

Any suggestions on solution, or next steps to trouble shoot?

**Comment by rogeriochaves** [comment]
Having the same problem here. Any solutions yet?

**Comment by gr2m** [comment]
> it then takes a long time (about 1 minute) for the Sign Up button to appear

At least that part is fixed now in https://github.com/hoodiehq/hoodie-server/tree/next/. The reasons is that the on-the-fly generated hoodie.js was very slow, and the UI was blocked until it was done. It was slow on the first two requests, it was cached afterwards.

Most likely, this is a problem with iriscouch, which was the source of a lot of hard to find bugs in the past :( Can you try using another CouchDB, e.g. your local one?

**Comment by rogeriochaves** [comment]
I've set up my own couchdb on an ec2 ubuntu instance (installing in other linux distributions is very hard) and it worked well. I don't recommend iriscouch, there are many bugs there.

**Comment by janl** [comment]
Closing because iriscouch and nodejitsu are defunkt
