### ISSUE TITLE
Cannot start server on some of the ports:

### ISSUE THREAD

**Issue by idanb11** [hoodiehq/hoodie-server#336]
Hi,

When i try to start hoodie with port 80, i get the following error:
`Version: 0.6.3 (node v0.10.33, npm 2.5.0, platform: linux)`

`[hoodie] Serving hoodie on custom ports 80,6005,6006`
`Initializing...`
`CouchDB started: http://127.0.0.1:6006`
`Waiting for CouchDB [--*---] SUCCESS`
`Error: listen EACCES`
`    at errnoException (net.js:904:11)`
`    at Server._listen2 (net.js:1023:19)`
`    at listen (net.js:1064:10)`
`    at net.js:1146:9`
`    at dns.js:72:18`
`    at process._tickDomainCallback (node.js:463:13)`

when i try the same thing with port 1081 for example, the hoodie server runs just fine.

Idanb11

**Comment by boennemann** [comment]
Hello @idanb11,

these are not just "some" ports, but the so called [system ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Well-known_ports). Binding a process to them usually requires admin rights, also indicated by the `EACCES` error code you're getting.

You can either try to use ports >1023, or use `sudo` to start the the application.

Best,
Stephan
