### ISSUE TITLE
error [EACCES, mkdir]

### ISSUE THREAD

**Issue by soomro** [hoodiehq/hoodie-server#339]
Version: 0.6.3 (node v0.12.0, npm 2.5.1, platform: darwin)

Initializing...

ERR! Error: EACCES, mkdir '/Users/USER/Git_Files/MYAPP_Hoodie/MYAPP/data'
ERR!     at Error (native)

Hello everyone. 
I am new to Hoodie, and this is my first app.
While running the app, i am getting this error.

When applied sudo, it gave following:
[hoodie] Hoodie does not support being run as sudo. Please try again.

What should i do?

**Comment by janl** [comment]
1. do not use `sudo` :)
2. `sudo chown -R $USER /Users/USER/Git_Files/MYAPP_Hoodie/`
3. try again.
4. really do not use `sudo` :)
