### ISSUE TITLE
Proposal: Remove Nodejitsu support

### ISSUE THREAD

**Issue by christophwitzko** [hoodiehq/hoodie-server#347]
Hi everyone,

Nodejitsu will be shutting down all services in September ([Nodejitsu joins GoDaddy](https://blog.nodejitsu.com/nodejitsu-joins-godaddy/)).

That means that there is no more need for the built-in [nodejitsu reverse proxy](https://github.com/hoodiehq/hoodie-server/blob/master/lib/server/nodejitsu_server.js).

By removing Nodejitsu support we should also consider to provide alternatives. I am thinking about [Heroku](https://www.heroku.com/), [AWS Elastic Beanstalk](http://aws.amazon.com/elasticbeanstalk/), Docker ([Cloud66](http://www.cloud66.com/), [Tutum](https://www.tutum.co/)), etc.

best regards,
Christoph

**Comment by janl** [comment]
Yeah, this is long overdue, I’m all in favour, if you want to tackle this :)

**Comment by christophwitzko** [comment]
I'm in. :relaxed: :+1:

**Comment by boennemann** [comment]
c4cb1795c094b0f2a449d735aab19b182929fcb7
