### ISSUE TITLE
Hoodie watch for plugins 

### ISSUE THREAD

**Issue by mmichelli** [hoodiehq/hoodie-server#350]
Reload pluggins as you update them, so we don't have to reload the server on each change.

**Comment by janl** [comment]
I think this is a great idea. To clarify, I’d first tackle this as an improvement for plugin developers, e.g. we don’t necessarily have to make sure this is a production-ready feature. Later, dynamic plugin updates would be nice. Are there other Node.js projects that do this, that we could steal ideas from?

**Comment by boennemann** [comment]
We'll rethink/tackle this once we've reintroduced plugins: https://github.com/hoodiehq/hoodie-server/issues/417
