### ISSUE TITLE
[CORS proxy] do not fallback access-control-allow-origin to *

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#353]
It is not allowed, if `access-control-allow-credentials` is set to `true`, which it is in our case. 

When `request.headers.origin` is not set, it usually means the request is coming from the same host, and no CORS headers should be set

**Comment by svozza** [comment]
I know this is marked as `later` but I could pick this up if no one objects?

**Comment by gr2m** [comment]
We are currently re-implementing hoodie-server, so it might be a non problem already, I'm not sure. If you are interested in CORS & hapi in general, I made a plugin that does that a while back: https://github.com/gr2m/hapi-cors-headers

If you'd like to contribute to Hoodie in general, here are some great open starter issues:
http://go.hood.ie/1OkPmfM

Please let me know if you have any farther questions :)

**Comment by boennemann** [comment]
Landed https://github.com/hoodiehq/hoodie-server/commit/67f6b686e3aa79e79666acc553699cf8728e9892
