### ISSUE TITLE
Move to new architecture

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-server#360]
Here is how we are going to do this:

For each repo, we:
- [x] create a new tag `before-1.0`
- [x] create a `next` branch
- [x] update package.json to include module name without `hoodie-` prefix, if applicable

Module Meta
- [x] install `semantic-release` with `semantic-release-cli`
- [ ] install `semantic-release` plugins (`verify-conditions`, `verify-release`)
- [x] add `hoodie-ci-result` dev dependency
- [x] add `standard` package
- [ ] fix `travis.yml`

Module Content
- [x] change `CONTRIBUTING.md` to point to https://github.com/hoodie/hoodie/CONTRIBUTING.md
   - “We are sorry to make you click one more time, but here are the [contribution guidelines](link)”
   - add hoodie dog image
- [x] change `TRIAGING.md` to point to https://github.com/hoodie/hoodie/TRIAGING.md
- [x] remove change log
- [x] remove `.jshintrc` & `.jshintignore`
- [x] port test startup from grunt to npm scripts
- [x] remove `Gruntfile.js`

READMEs
- [x] READMEs don’t include docs
- [ ] fixed README structure (structure TDB, focussing on contributing), minimal “Usage” section where applicable
- [ ] README contributing sections: badges, first contacts (2), chat, usage
- [ ] sub-READMEs in every sub folder explaining briefly what is going on there

Directory structure:
- depends on type of module

**Comment by boennemann** [comment]
The checklist doesn't 100% reflect what we had to do, but we're running on the new architecture™ now.
