### ISSUE TITLE
 High CPU/Mem and lag when requesting _api/_files/hoodie.js on server v4.0.3

### ISSUE THREAD

**Issue by inator** [hoodiehq/hoodie-server#366]
Hello gang -

I thought I'd give the latest a try and noticed that requesting the hoodie.js file results in extreme lag on an Ubuntu host.  CPU gets pegged and and memory shoots very high.  Eventually, the resource is returned, but it can take the better part of a minute.

@jan Side note:  Aside from this, I'm encouraged, as the memory use at idle seems very stable (testing to see if the memory leak issue #280 has been resolved), but I won't know for sure until I can utilize via the frontend and get some typical use.

**Comment by janl** [comment]
The new architecture won’t have plugins at first, so we’ll not be tackling this before then.

**Comment by boennemann** [comment]
This is now serving a static, precompiled file, thus no more heave computation involved.

**Comment by inator** [comment]
Way to go @boennemann!
