### ISSUE TITLE
[next] npm run test:integration:manager fails if couchdb daemon process is running

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#368]
To reproduce

1. CouchDB deamon is started on startup for me. To manually start it as deamon, I've to run `launchctl load ~/Library/LaunchAgents/homebrew.mxcl.couchdb.plist`
2. Verify that it runs with `ps x | grep couchdb`
3. `npm run -s test:integration:manager`

To stop the deamon, I had to run `launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.couchdb.plist`. If I run `npm run -s test:integration:manager` after that, all tests are passing fine.

**Comment by boennemann** [comment]
no more couchdb :)
