### ISSUE TITLE
stream uploads 

### ISSUE THREAD

**Issue by mmichelli** [hoodiehq/hoodie-server#370]
Is there any reason not to have  output: 'stream' for uploads? 
Or away for the plugins to change the setting? 

https://github.com/hoodiehq/hoodie-server/blob/abd4ed278cbe9c9a674ecc105be17e319ebaecd0/lib/server/index.js#L15

**Comment by espy** [comment]
This is something @boennemann or @gr2m would be able to answer…

**Comment by gr2m** [comment]
I couldn't think of an reason, but I'm also not an expert here. Can you explain your use case for a better understanding of the context? How would `output: 'stream'` help?

**Comment by boennemann** [comment]
@mmichelli Could you please elaborate some more? Why do you want to set that and what's a possible use case?

It's easier for us to answer your question and eventually implement a fix.

Thank you,
Stephan

**Comment by mmichelli** [comment]
Sorry I missed the updates. 

Use case: 
I use the streaming for a file upload plugin, files get uploaded, and it is an image then scaled and cropped and then streamed to a cloud service. 

I would be happy with: 
Either add stream to the config, or allow me to change the server setting without hacking the plugin.

**Comment by boennemann** [comment]
We removed the payload limit, so future plugins can handle this on their own.
