### ISSUE TITLE
New Plugin Architecture

### ISSUE THREAD

**Issue by christophwitzko** [hoodiehq/hoodie-server#379]
Hi folks,

I gave the new hoodie plugin architecture some thought.
As an example I applied the new architecture to `hoodie-plugin-test`: https://github.com/hoodiehq/hoodie-plugin-test/tree/new-plugin-architecture

## frontend
> `frontend/index.js` or `frontend.js`

I am really unsure about this part. At the moment the frontend module exports a function that looks like this:

```javascript
module.exports = function (hoodie) {
  // modify the hoodie object
}
```

I really do not know if it is a good idea to give every plugin the possibility to modify the global hoodie object.

## backend
> `backend/index.js` or `backend.js`

In my opinion we could just leave it as it is. (Except for renaming the files from `worker.js` or `index.js` to `backend.js`)

### static hooks
> `hooks/static/index.js` or `hooks/static.js`

At the moment static hooks are not really used and also the `server.pack.pre` and `server.pack.post` events does not make any sense to me.
I think static hooks should be pure hapi-plugins: https://github.com/hoodiehq/hoodie-plugin-test/blob/new-plugin-architecture/hooks/static.js

### dynamic hooks
> `hooks/dynamic/index.js` or `hooks/dynamic.js`

The biggest changes happened to the dynamic hooks.
The dynamic hook initialization function gets passed a hoodie plugin event emitter and a callback: https://github.com/hoodiehq/hoodie-plugin-test/blob/new-plugin-architecture/hooks/dynamic.js

The old hook system also checked the return value of `server.api.plugin-request`.

> false determines that the hook didn’t run successfully and causes Hoodie to return a 500 error.

In my mind that does not really make sense because it will not work with asynchronous code.

Have a nice day,
Christoph

**Comment by boennemann** [comment]
## frontend

in order to use stay consistent with the browserify terminology I'd prefer browser{.js,/index.js}

## backend

I'd remove any rules or here, except for this: "What we get by `require`ing your plugin". Conventions will follow.

## hooks

great changes, but maybe we can also make the naming clearer. "static hooks" if they are just hapi plugins might as well have a name that reflects this.

**Comment by gr2m** [comment]
### frontend

I'd suggest we have a `hoodie.plugin` method in the client core, which accepts a function to which we pass the `hoodie` API so we can do what ever we want with it. We could also support the PouchDB way to pass a key/value map which works like [PouchDB's plugin method](http://pouchdb.com/api.html#plugins)

The reason why I'd like to keep the `function (hoodie) {}` way is that in some cases you don't want to extend the `hoodie` API at all, sometimes you want to add multiple methods, sometimes thing depend on the current client configuration. I wouldn't like to limit the eco system.

Also, I'd suggest we call it client, not frontend or browser. So plugins would have `client.js` or `client/index.js`. Extending the client is optional.

### backend

Can we call the backend part "server", so plugins would have `server.js` or `server/index.js`. Extending the server is optional
