### ISSUE TITLE
Serve `my-first-hoodie` if specified `www` doesn't exist/contain `index.html`

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/hoodie-server#382]
As part of making the new `npm install hoodie` process as easy and straightforward as possible I'd like to introduce the following behavior/check:

When the specified `www` path option doesn't exist/contain an index.html file (and the `NODE_ENV !== 'production`) I'd like to serve the `my-first-hoodie` app.

This would be another friendly default (rather than just a 404 straight in your face) and a great opportunity to provide helpful information for starters.

On a technical level this would require depending on `my-first-hoodie` and adding it to the bundle. A neglect-able cost for the improvement of the dev experience.

**Comment by Charlotteis** [comment]
This sounds like a great idea; I think we should also log a message to the console saying something like "Sorry! The path provided does not exist, using the my-first-hoodie template instead"
