### ISSUE TITLE
POST http://127.0.0.1:6004/_api/_session 401 (Unauthorized) when logging in with wrong credentials

### ISSUE THREAD

**Issue by JanaFlauschata** [hoodiehq/hoodie-server#406]
I'm a new Hoodie user and wondering about the following issue:

When I try to login with wrong credentials I get the following error in the browser log (on top of the expected error resulting from the unsuccesful signin):

POST http://127.0.0.1:6004/_api/_session 401 (Unauthorized)

The same occurs for the todo test app.

Is this a problem with my setup?
Or is this an exception which is not caught properly? Of course I don't expect to be authorized since I did not log in properly, but it is not an exceptional state and should be dealt with by the hoodie login functions, doesn't it...?

I would really appreciate some feedback in case I have problems with my setup.

Thanks!

**Comment by JanaFlauschata** [comment]
Sorry, for mixing up the repositiories. It would be great if someone could move my post to https://github.com/hoodiehq/hoodie-plugin-users/issues.

Some additional information: there's no problem with signup/in/out in general. That is working smoothly. I just don't understand where the said exception originates from and whether it is a general thing or has to do something with my setup.

**Comment by boennemann** [comment]
Moved to hoodie-plugin-users: https://github.com/hoodiehq/hoodie-plugin-users/issues/50
