### ISSUE TITLE
[idea] [hoodie-plugins-api] provide user context everywhere

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-server#408]
One of the things where Hoodie is very different from other server side frameworks is that we don’t run dynamic request-respond cycles with an authenticated browsers. In traditional backends, I always have a  user context around, that I know something needs to act on (e.g. send an email) and I can check all sorts of stuff against that user context (e.g. is this user allowed to send emails).

The Hoodie backend is all asynchronous and doesn’t work in an authenticated browser session. It runs as an event-based handler that does things when instructed. Say we want to send an email, our email send code gets invoked by an email task, but in that task we have no way to check, whether that user is even allowed to send emails, easily. Of course users can work around that, but it feels clumsy.

I’d like to propose that we consider putting backend events in a user context,, so that plugin authors can make all the decisions they need to make like they would with other backends.

I don’t have a dreamcode API yet, but I presume something like this.

Current task api:

```js
 hoodie.task.on('email:add', function(dbName, email) {...}
```

Possible new alternative with user context:

```js
 hoodie.task.on('email:add', function(task, user) {
    task = {
      email: { /* old email object */},
      dbName: 'old_db_name'
    }

    user = {
      id: 'hoodieId',
      email: 'emailAddress',
      roles: [..],
      ... // essentially the _users doc, but maybe even more data, or even convenience methods to call,
    }
}
```

What do you think?

**Comment by gr2m** [comment]
I think that makes a lot of sense. Also note that new Hoodie will have all tasks in the same database, there won't be stored in user databases any longer, so the `dbName` info will be obsolete

**Comment by boennemann** [comment]
Moved https://github.com/hoodiehq/hoodie-server-account/issues/14
