### ISSUE TITLE
hapi-couchdb-account-api

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#410]
all the account routes have been extracted into its own plugin: https://github.com/hoodiehq/hapi-couchdb-account-api

So no need to load https://github.com/hoodiehq/hapi-couchdb-account anymore.

**Comment by gr2m** [comment]
the repo is called hoodie-server-account now

**Comment by boennemann** [comment]
Landed https://github.com/hoodiehq/hoodie-server/commit/f917f271056e86b1da1985dd17d6be9bd4207895
