### ISSUE TITLE
error:unauthenticated is not triggered while using the app

### ISSUE THREAD

**Issue by rogeriochaves** [hoodiehq/hoodie-server#413]
Hello,

So, I create a new instance of hoodie (`new Hoodie('HOODIE_URL')`) when the page is loaded, and I listen to `error:unauthenticated` events, but apparently this event is only triggered when the session is expired and the user reloads the page.

I put my couchdb session to expire in 15s just to test, and when the user is using the app, after 15s, the data syncing starts to throw 401s, and the user can't logout, but no `error:unauthenticated` is triggered, only if I reload the page.

Thanks!

**Comment by gr2m** [comment]
Hey @rogeriochaves, that will be resolved with the new Hoodie that we are currently working on, I can't say when it's ready to play with, but we are making great progress. Is this a big issue for you or can it wait for the new Hoodie?

**Comment by rogeriochaves** [comment]
It's not a big issue right now, thanks for the concern.

Is this already on the next branch or is something planned?

**Comment by gr2m** [comment]
This specific part is not yet implemented. We'll need to implement it in https://github.com/hoodiehq/hoodie-client. When ever there is an "unauthenticated" error in the `hoodie.store` module, we should call `account.get()`, which then should also fail and then emit the `error:unauthenticated` event on `hoodie.account`, as documented here: https://github.com/hoodiehq/account-client

**Comment by boennemann** [comment]
moved over https://github.com/hoodiehq/hoodie-client/issues/27
