### ISSUE TITLE
Temporarily remove plugin API 

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/hoodie-server#417]
As per the new [core component structure](https://github.com/hoodiehq/hoodie/pull/435) all core components (store, account, task) will be part of hoodie core. They are no longer using the public plugin API.

This means we could leave the plugin API temporarily out of hoodie-server to focus on consolidating the rewritten core components first. We can reintroduce/rethink/reimplement the plugin API at a point where the rest (i.e. core) is stabilized.

This would allow us to move forward faster. The current plugin implementation constitutes a huge part of the codebase and build-time, it's complicated and not written by anyone currently maintaining hoodie.
Along with the API itself we could remove the plugin loading, relevant config, relevant routes, the hooks implementation and browserifying/bundling.

We'd be left with a very lean and testable hoodie-server that essentially serves as a top-level hub to combine individual components, ensuring correct database setup and common configuration.

**Comment by christophwitzko** [comment]
:+1:

**Comment by gr2m** [comment]
:+1:

**Comment by HipsterBrown** [comment]
:+1:

**Comment by janl** [comment]
Sounds good to me!

**Comment by Charlotteis** [comment]
bit late, but :+1:

**Comment by louisremi** [comment]
I haven't built a lot of different plugins, but having spent quite some time on our [Stripe](https://github.com/byte-foundry/hoodie-plugin-stripe-subscriptions) plugin lately. I'm becoming more and more frustrated by the fact that plugins are node modules that can only be updated by restarting the hoodie app.

From what I've seen from Next, you're trying to expose many features that were only available for plugins through the hoodie object, as REST APIs, right? I believe this is the way to go. I wish I could rewrite our Stripe plugin as an external micro-service sending authenticated requests to an account REST API. Ideally, I wish I could configure external endpoints that Hoodie would ping on different event, as an alternative to the `hoodie.*.on('...', function () { ... })` api.
