### ISSUE TITLE
rename /www to /public

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#436]
The main reason why I’d like to rename /www to /public is that it’s www is really hard to pronounce in English :) When giving a talk or during a screencast, it’s _so much easier_ to refere to the "public folder" compared to "www folder".

"public" also feels like more common to refer to an asset folder, I know it from Rails. I think www is coming from Apache server config?

Anyway, any objects / good reason to not rename the folder to `/public`?

**Comment by janl** [comment]
www == dub dub dub

**Comment by janl** [comment]
I’m not averse to renaming, but we should look at other places and see what we think is most intuitive.

Common names for things like this that I can remember off the top of my head:
- `www`
- `html`
- `static`
- `public`
- `dist` (probably more common as a compile target location)
- `htdocs` (the default name from the Apache httpd server)
- `public_html` (What the Apache Software Foundation uses on their infrastructure)
- `site`
- `_site` (Jekyll, also a compile target)
- `Sites` (Mac OS X)

**Comment by nickcolley** [comment]
public has the benefit of describing itself as the only thing available to your users.

**Comment by gr2m** [comment]
I’d remove this from the list

- Sites – implies there would be multiple sites, which we won’t whave
- _site, site – hoodie is more about apps, site sounds more like content page
- htdocs – is very technical and would need an explanation what it is, to our target group at least
- dist – would also need an explanation

Less confusing but limiting

- html
- public_html
- www

these are more clear to me

- public
- static

And of these, public is the clearest to me, closest to natural language. You wouldn’t say "If you want to make something statically available". You would say "publicly available". Pretty much what Nick says :)

**Comment by boennemann** [comment]
If in doubt I'd always stick with what's common in the ecosystem.

Both [hapi](http://hapijs.com/tutorials/serving-files#directory-handler) and [express](http://expressjs.com/en/starter/static-files.html) are naming such a folder "public" in their docs. Reason enough for me :)

**Comment by gr2m** [comment]
We don’t have public process for decision making at Hoodie yet: but okay if I wait until Tuesday, so we had 3 work days waiting for feedback, and if there is no objection we go with the `/public` folder?

Related: I keep a list of open discussion items for new Hoodie here: https://github.com/gr2m/milestones/issues/88#discussion

**Comment by janl** [comment]
`public` is fine by me :)

**Comment by gr2m** [comment]
done via  https://github.com/hoodiehq/hoodie-server/issues/477 and https://github.com/hoodiehq/hoodie-app-tracker/issues/34
