### ISSUE TITLE
Make the fallback webapp shown at /hoodie more helpful

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#478]
If a Hoodie app has no `public/` folder, we serve this: https://github.com/hoodiehq/hoodie-server/tree/tent/public

This could be much more helpful. I could explain why it is shown (because your app has no `public/` folder), it could load `<script src="/hoodie/client.js"></script>` and tell if it is loaded correctly, it could show the hoodie version, it could link to docs etc.

**Comment by sebbel** [comment]
What would be more helpful? Maybe a short walkthrough how to get going with a fresh hoodie-application, for example 

- creating a public directory 
- including the hoodie/client.js in the html file, where hoodie should be used.
- overview of hoodie.store and/or hoodie.account functions

**Comment by gr2m** [comment]
That sounds great :) I’d suggest we just go ahead with your ideas, see how it feels and iterate?

**Comment by sebbel** [comment]
That sounds like a plan! I've forked and will provide a PR shortly.

**Comment by gr2m** [comment]
closed via #484

**Comment by gr2m** [comment]
I’ve invited you to the Hoodie Contributors Team :tada: you should see an invitation on https://github.com/hoodiehq. Welcome!

**Comment by sebbel** [comment]
Awesome! Thanks alot :)
