### ISSUE TITLE
ECONNREFUSED after I close my laptop

### ISSUE THREAD

**Issue by bbn** [hoodiehq/hoodie-server#51]
Running locally my hoodie app is amazeballs! 
And then I close my laptop. 
And then later I open it up, and I get
stuff that looks like this in my console: http://cl.ly/image/2f0P2b0U1R3K

The response from the call to _api/ is: 
    
    An error has occurred: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}

**Comment by boennemann** [comment]
No more couchdb starting in hoodie-server
