### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by millisami** [hoodiehq/hoodie-server#510]
Followed the Readme and started `hoodie new appName -t "hoodiehq/hoodie-app-skeleton" `.
But when i start the server, this error is killing me.

https://gist.github.com/millisami/0b8d2b621fb39ad2c5b0cccd7d165493

Why is this?
I am on mac book pro and the node versions:
```
Now using io.js v2.3.0 (npm v2.11.1)
```

**Comment by gr2m** [comment]
hey @millisami, your node version is very out of date. Can you please install the latest node from https://nodejs.org/en/?

Also you are using the old hoodie version. I’m very sorry for the confusion, we are currently transitioning to a new Hoodie, and the old version is still referenced a lot on our website and the docs. 

After you installed the new Node version, follow the setup instructions at https://github.com/hoodiehq/hoodie. Here is a simple example app that you can check out to see Hoodie works https://github.com/hoodiehq/hoodie-app-tracker. And the work-in-progress docs are here: http://docs.hood.ie/camp/ (note the `/camp` path)
