### ISSUE TITLE
Error confirming user: Error: not_found in my local dev machine

### ISSUE THREAD

**Issue by millisami** [hoodiehq/hoodie-server#511]
When starting my new hoodie app, this is freaking me out.

```
Initializing...
Using remote CouchDB: http://127.0.0.1:5984
Waiting for CouchDB [-*----] SUCCESS
WWW:    http://127.0.0.1:6001
Admin:  http://127.0.0.1:6002
Starting Plugin: 'hoodie-plugin-appconfig'
Starting Plugin: 'hoodie-plugin-email'
Starting Plugin: 'hoodie-plugin-users'
All plugins started.

Error confirming user: Error: not_found
missing
{ [Error: not_found
missing]
  error: 'not_found',
  reason: 'missing',
  response:
```
Full output at: https://gist.github.com/millisami/f175513badc336e88fcb338884e703b5

Now using io.js v2.3.0 (npm v2.11.1)
Couchdb installed via brew and installed `1.6.x` version.

**Comment by gr2m** [comment]
please see my commment here: https://github.com/hoodiehq/hoodie-server/issues/510#issuecomment-250578620
