### ISSUE TITLE
Issue with hoodie start: Timed out waiting for CouchDB

### ISSUE THREAD

**Issue by fokusferit** [hoodiehq/hoodie-server#523]
Hi everyone,

I just wanted to try out hoodie and I followed the documentation to the point where I can just start my application. Sadly, I'm not able to start it as it says that there is an issue with CouchDB:

My environment:
MacOS Sierra 10.12.1 (16B2555)
Node v6.5.0 (not the newest one but I guess this is not the issue here, just a guess). 
npm 3.10.0
CouchDB is installed via Installer from the official page, it is in my Applications folder and I can open the Fauxton Page (+verify Installation).

When I do `hoodie start` in the project folder this is the output:
Version: 0.6.3 (node v6.5.0, npm 2.15.11, platform: darwin)

> Initializing...
> (node:64606) DeprecationWarning: sys is deprecated. Use util instead.
> CouchDB started: http://127.0.0.1:6006
> Waiting for CouchDB [---*--] FAILED 
> 
> ERR! Error: Timed out waiting for CouchDB. These logs may help:
> ERR! 	/Users/fetopcu/Desktop/Projects/logStore/data/couch.stderr
> ERR! 	/Users/fetopcu/Desktop/Projects/logStore/data/couch.stdout
> ERR! 	/Users/fetopcu/Desktop/Projects/logStore/data/couch.log
> ERR!     at Request._callback (/Users/fetopcu/Desktop/Projects/logStore/node_modules/hoodie-server/lib/couchdb/index.js:145:27)
> ERR!     at self.callback (/Users/fetopcu/Desktop/Projects/logStore/node_modules/hoodie-server/node_modules/request/request.js:197:22)
> ERR!     at emitOne (events.js:96:13)
> ERR!     at Request.emit (events.js:188:7)
> ERR!     at Request.onRequestError (/Users/fetopcu/Desktop/Projects/logStore/node_modules/hoodie-server/node_modules/request/request.js:854:8)
> ERR!     at emitOne (events.js:96:13)
> ERR!     at ClientRequest.emit (events.js:188:7)
> ERR!     at Socket.socketErrorListener (_http_client.js:308:9)
> ERR!     at emitOne (events.js:96:13)
> ERR!     at Socket.emit (events.js:188:7)
> 
> Stopping CouchDB...

And this is the output of my couch.stderr:

> Protocol 'inet_tcp': the name couchdb@localhost seems to be in use by another Erlang node
> Protocol 'inet_tcp': the name couchdb@localhost seems to be in use by another Erlang node
> Protocol 'inet_tcp': the name couchdb@localhost seems to be in use by another Erlang node
> Protocol 'inet_tcp': the name couchdb@localhost seems to be in use by another Erlang node
> [info] 2016-12-19T14:27:17.408539Z couchdb@localhost <0.9.0> -------- Application couch_log started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.421811Z couchdb@localhost <0.9.0> -------- Application folsom started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.490433Z couchdb@localhost <0.9.0> -------- Application couch_stats started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.490584Z couchdb@localhost <0.9.0> -------- Application khash started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.513647Z couchdb@localhost <0.9.0> -------- Application couch_event started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.523652Z couchdb@localhost <0.9.0> -------- Application ibrowse started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.538223Z couchdb@localhost <0.9.0> -------- Application ioq started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.538384Z couchdb@localhost <0.9.0> -------- Application mochiweb started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.538519Z couchdb@localhost <0.9.0> -------- Application oauth started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.551580Z couchdb@localhost <0.205.0> -------- Apache CouchDB 2.0.0 is starting.
> 
> [info] 2016-12-19T14:27:17.551650Z couchdb@localhost <0.206.0> -------- Starting couch_sup
> [notice] 2016-12-19T14:27:17.637046Z couchdb@localhost <0.90.0> -------- config: [couchdb] uuid set to 8019c14125ccd5fb3d79c61e4e4f715f for reason nil
> [info] 2016-12-19T14:27:17.703252Z couchdb@localhost <0.211.0> -------- open_result error {not_found,no_db_file} for _users
> [info] 2016-12-19T14:27:17.846463Z couchdb@localhost <0.205.0> -------- Apache CouchDB has started. Time to relax.
> 
> [info] 2016-12-19T14:27:17.846582Z couchdb@localhost <0.205.0> -------- Apache CouchDB has started on http://127.0.0.1:5986/
> [info] 2016-12-19T14:27:17.846727Z couchdb@localhost <0.9.0> -------- Application couch started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.846867Z couchdb@localhost <0.9.0> -------- Application ets_lru started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.872114Z couchdb@localhost <0.9.0> -------- Application rexi started on node couchdb@localhost
> [info] 2016-12-19T14:27:17.906440Z couchdb@localhost <0.211.0> -------- open_result error {not_found,no_db_file} for _nodes
> [info] 2016-12-19T14:27:17.992509Z couchdb@localhost <0.211.0> -------- open_result error {not_found,no_db_file} for _dbs
> [error] 2016-12-19T14:27:17.992708Z couchdb@localhost emulator -------- Error in process <0.293.0> on node couchdb@localhost with exit value:
> {{badmatch,file_exists},[{mem3_shards,fold,2,[{file,"src/mem3_shards.erl"},{line,156}]},{mem3_sync,initial_sync,1,[{file,"src/mem3_sync.erl"},{line,241}]}]}
> 
> [info] 2016-12-19T14:27:18.008877Z couchdb@localhost <0.9.0> -------- Application mem3 started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.008936Z couchdb@localhost <0.9.0> -------- Application fabric started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.044191Z couchdb@localhost <0.9.0> -------- Application chttpd started on node couchdb@localhost
> [notice] 2016-12-19T14:27:18.060912Z couchdb@localhost <0.331.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
> [error] 2016-12-19T14:27:18.060988Z couchdb@localhost emulator -------- Error in process <0.332.0> on node couchdb@localhost with exit value:
> {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,331}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,87}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}
> 
> [info] 2016-12-19T14:27:18.066366Z couchdb@localhost <0.9.0> -------- Application couch_index started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.066438Z couchdb@localhost <0.9.0> -------- Application couch_mrview started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.066461Z couchdb@localhost <0.9.0> -------- Application couch_plugins started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.080143Z couchdb@localhost <0.211.0> -------- open_result error {not_found,no_db_file} for _replicator
> [notice] 2016-12-19T14:27:18.114081Z couchdb@localhost <0.350.0> -------- creating replicator ddoc
> [info] 2016-12-19T14:27:18.151375Z couchdb@localhost <0.9.0> -------- Application couch_replicator started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.151494Z couchdb@localhost <0.9.0> -------- Application couch_peruser started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.160370Z couchdb@localhost <0.9.0> -------- Application ddoc_cache started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.179867Z couchdb@localhost <0.9.0> -------- Application global_changes started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.179940Z couchdb@localhost <0.9.0> -------- Application jiffy started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.188363Z couchdb@localhost <0.9.0> -------- Application mango started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.196702Z couchdb@localhost <0.9.0> -------- Application setup started on node couchdb@localhost
> [info] 2016-12-19T14:27:18.196760Z couchdb@localhost <0.9.0> -------- Application snappy started on node couchdb@localhost
> [notice] 2016-12-19T14:27:23.064055Z couchdb@localhost <0.331.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
> [error] 2016-12-19T14:27:23.064213Z couchdb@localhost emulator -------- Error in process <0.458.0> on node couchdb@localhost with exit value:
> {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,331}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,87}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}
> 
> [notice] 2016-12-19T14:27:28.070463Z couchdb@localhost <0.331.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
> [error] 2016-12-19T14:27:28.070700Z couchdb@localhost emulator -------- Error in process <0.555.0> on node couchdb@localhost with exit value:
> {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,331}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,87}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}
> 
> [notice] 2016-12-19T14:27:33.076506Z couchdb@localhost <0.331.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
> [error] 2016-12-19T14:27:33.076712Z couchdb@localhost emulator -------- Error in process <0.620.0> on node couchdb@localhost with exit value:
> {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,331}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,87}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}
> 
> Protocol 'inet_tcp': the name couchdb@localhost seems to be in use by another Erlang node
> [notice] 2016-12-19T14:27:38.080547Z couchdb@localhost <0.331.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
> [error] 2016-12-19T14:27:38.080715Z couchdb@localhost emulator -------- Error in process <0.717.0> on node couchdb@localhost with exit value:
> {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,331}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,87}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}
>

**Comment by gr2m** [comment]
Hey @fokusferit, we have a new version of Hoodie which we will replace the one you used very soon, we just have to update documentation. Could you follow these instructions and see if that works for you? https://github.com/hoodiehq/hoodie#setup

Also uninstall the old hoodie CLI with `npm uninstall --global hoodie-cli`

**Comment by fokusferit** [comment]
@gr2m thanks for the update. The new setup is working fine 👍
