### ISSUE TITLE
Connect hoodie-client to hoodie-server using websockets?

### ISSUE THREAD

**Issue by IamCarbonMan** [hoodiehq/hoodie-server#534]
Would it be possible to use something like [socket-pouch](https://github.com/nolanlawson/socket-pouch) or [pouch-websocket-sync](https://github.com/pgte/pouch-websocket-sync) for the Hoodie connection?

**Comment by gr2m** [comment]
no, not at this point. But we use long poll request for remote data changes, so it’s pretty similar. Could you explain your use case why you need / prefer websockets?

**Comment by IamCarbonMan** [comment]
Websockets outperform long polling, especially when data changes frequently. Also, websockets are a standardized technology which will continue to grow and be supported by the community.

**Comment by gr2m** [comment]
I’ve heard otherwise, but I don’t know all the technical details on it. I’ll reach out to some folks who know better to provide information on it, it might take a few days though :)

**Comment by janl** [comment]
We use continuous changes feeds, so same characteristics as WS, not long polling. In addition, we've seen quite a number of issues with "transparent" proxies, especially on mobile, that don't do WS.

While there are still some scenarios where WS were advantageous, it's not worth the effort and issues for us.

The future for this typenof stuff is HTTP2, and we'll get that support for free as soon as our underlyinng components get them.

**Comment by IamCarbonMan** [comment]
> We use continuous changes feeds, so same characteristics as WS

If I understand CouchDB, continuous feeds use HTTP streaming under the hood, right?

**Comment by janl** [comment]
> If I understand CouchDB, continuous feeds use HTTP streaming under the hood, right?

In essence yes, here’s the words I’d choose: It is an open TCP socket with a HTTP header that gets kept open indefinitely that gets sent down a line of JSON per event happening in CouchDB.

**Comment by IamCarbonMan** [comment]
So yeah, just as good as WS for this use case. Thanks for clearing that up.
