### ISSUE TITLE
Nodejitsu startup and admin users

### ISSUE THREAD

**Issue by caolan** [hoodiehq/hoodie-server#64]
On Nodejitsu, don't prompt for _admin when stored credentials are not working/missing. It should report a meaningful error message and exit instead since we can't use a prompt during a deployment. Also, do NOT generate a new internal hoodie admin and password if none set using environment variables, the randomly generated password is likely to be lost, potentially locking you out. Instead, always demand that HOODIE_ADMIN_USER and HOODIE_ADMIN_PASS are set.

Consider how to handle the creation of the user's admin account for pocket. This may have to be handled using environment variables too in the short term, but ideally we'd start-up in some kind of admin party mode like CouchDB.

**Comment by boennemann** [comment]
nodejitsu support dropped, therefor this is no longer relevant
